version: '3'
services:
#mssql docker
  bhfudbal-sql:
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1433:1433
    networks:
      - bhfudbalnet2023

  bhfudbal-api:
    restart: unless-stopped
    build:
      context: .
    ports:
      - 5001:5001
    networks:
      - bhfudbalnet2023
    links:
      - bhfudbal-sql
    depends_on:
      - bhfudbal-sql

  rabbitmq: # login guest:guest
    image: rabbitmq:3-management
    hostname: "rabbitmq"
    labels:
      NAME: "rabbitmq"
    ports:
    - "4369:4369"
    - "5671:5671"
    - "5672:5672"
    - "25672:25672"
    - "15671:15671"
    - "15672:15672"
    networks:
      - bhfudbalnet2023
    links:
      - bhfudbal-api
    depends_on:
      - bhfudbal-api
    
  console-app:
    build:
      context: .
      dockerfile: ./BHFudbal.Subscriber/Dockerfile
    networks:
      - bhfudbalnet2023
    links:
      - bhfudbal-api
    depends_on:
      - bhfudbal-api
      - bhfudbal-sql
      - rabbitmq

      
networks:
  bhfudbalnet2023:
    driver: bridge   